channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.1
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.4
name: mlflow-env
